config/routes.rb
Rails.application.routes.draw do
  resources :meeting_employees
  resources :meetings do
    collection do 
      get 'json_meeting'
      # get 'json_test'
    end
  end
  resources :employees do
    collection do
      get 'json_employee'
    end
  end
  
  get 'meetings/:id/json_employee', to: 'meetings#json_employee'
  get 'meetings/:id/json_test', to: 'meetings#json_test'

  get 'index' => 'welcome#index'
  get 'index' => 'meetings#index'
  get 'welcome/new'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
	has_many :meeting_employee, :dependent => :delete_all
	has_many :meeting, :through => :meeting_employee


end

app/models/meeting.rb
class Meeting < ApplicationRecord
	has_many :meeting_employee, :dependent => :delete_all
	has_many :employee, :through => :meeting_employee


	def employees

		@employees = Meeting.find(id).employee
			return @employees
		
	end

end

app/models/meeting_employee.rb
class MeetingEmployee < ApplicationRecord
  belongs_to :meeting
  belongs_to :employee

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  def emp_meeting
    @employee = Employee.find(params[:id])
  end

  # GET /employees/json_employee 
  def json_employee
    @employee =  Employee.meeting.as_json
    puts @employee
    render json: @employee 
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :lastname, :sex, :start, :end)
    end
end

app/controllers/meeting_employees_controller.rb
class MeetingEmployeesController < ApplicationController
  before_action :set_meeting_employee, only: [:show, :edit, :update, :destroy]

  # GET /meeting_employees
  # GET /meeting_employees.json
  def index
    @meeting_employees = MeetingEmployee.all
  end

  # GET /meeting_employees/1
  # GET /meeting_employees/1.json
  def show
  end

  # GET /meeting_employees/new
  def new
    @meeting_employee = MeetingEmployee.new
  end

  # GET /meeting_employees/1/edit
  def edit
  end

  # POST /meeting_employees
  # POST /meeting_employees.json
  def create
    @meeting_employee = MeetingEmployee.new(meeting_employee_params)

    respond_to do |format|
      if @meeting_employee.save
        format.html { redirect_to @meeting_employee, notice: 'Meeting employee was successfully created.' }
        format.json { render :show, status: :created, location: @meeting_employee }
      else
        format.html { render :new }
        format.json { render json: @meeting_employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meeting_employees/1
  # PATCH/PUT /meeting_employees/1.json
  def update
    respond_to do |format|
      if @meeting_employee.update(meeting_employee_params)
        format.html { redirect_to @meeting_employee, notice: 'Meeting employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting_employee }
      else
        format.html { render :edit }
        format.json { render json: @meeting_employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meeting_employees/1
  # DELETE /meeting_employees/1.json
  def destroy
    @meeting_employee.destroy
    respond_to do |format|
      format.html { redirect_to meeting_employees_url, notice: 'Meeting employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting_employee
      @meeting_employee = MeetingEmployee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_employee_params
      params.require(:meeting_employee).permit(:meeting_id, :employee_id)
    end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end


  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  def json_meeting
    @meeting =  Meeting.all.as_json
    render json: @meeting 
  end

  def json_employee
    @meeting = Meeting.find(params[:id])
  end

  def emp_meeting
    @meeting = Meeting.find(params[:id])
  end

  def json_test
    @meeting = Meeting.find(params[:id]).employee.as_json
    # @start = Meeting.find(params[:id]).start
    # @end = Meeting.find(params[:id]).end
    # puts @start
    # puts @end
    render json: @meeting
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end


  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update



    respond_to do |format|
      if @meeting.update(meeting_params)
        
        # puts "Entra aqui"
        format.html { redirect_to :index }
        # format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:title, :start, :end, :color)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/meeting_employees_helper.rb
module MeetingEmployeesHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :employee_name %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname, id: :employee_lastname %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.text_field :sex, id: :employee_sex %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.time_field :start, id: :employee_start %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.time_field :end, id: :employee_end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Sex</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.lastname %></td>
        <td><%= employee.sex %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @employee.lastname %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @employee.sex %>
</p>

<p>
	<strong>Start:</strong>
	<%= @employee.start.strftime("%I:%M%p") %>
</p>

<p>
	<strong>End:</strong>
	<%= @employee.end.strftime("%I:%M%p") %>
</p>

<p>
	<table class="table">
		<thead>
			<tr>
    			<th scope="col">ID</th>
    			<th scope="col">Title</th>
    			<th scope="col">Color</th>
    			<th scope="col">Start</th>
    			<th scope="col">End</th>
    		</tr>
		</thead>
		<tbody>
			<% @employee.meeting.each do |mee| %>
	  	  		<tr>
      				<th scope="row"><%= mee.id %></th>
			    	<td><%= mee.title %></td>
			    	<td><%= mee.color %></td>
			    	<td><%= mee.start %></td>
			    	<td><%= mee.end %></td>
    			</tr>
			<% end %>
		</tbody>
	</table>
	
</p>

<!-- <p><%= link_to "#newTag",  data: { toggle: "modal" } do %>
  			<i class="fa fa-plus"></i> Ver Eventos 
		<% end %></p>

		<div id="newTag" class="modal fade" role="dialog">
		  <div class="modal-dialog">
		    <div class="modal-content">
		      <div class="modal-header">
		      	<h2>Eventos</h2>
		        <button type="button" class="close" data-dismiss="modal">&times;</button>
		      </div>
		      <div class="modal-body">
	      	  	<table class="table">
					<thead>
    					<tr>
			    			<th scope="col">ID</th>
			    			<th scope="col">Title</th>
			    			<th scope="col">Color</th>
			    		</tr>
  					</thead>
		
					<tbody>
						<% @employee.meeting.each do |mee| %>
				  	  		<tr>
			      				<th scope="row"><%= mee.id %></th>
						    	<td><%= mee.title %></td>
						    	<td><%= mee.color %></td>
						    	<td><%= mee.start %></td>
								<td><%= mee.end %></td>
			    			</tr>
    					<% end %>
					</tbody>
				</table> 	 
		      </div>
		    </div>
		  </div>
		</div> -->

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Database</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

	<div>
    <nav class="navbar navbar-dark navbar-expand-lg navbar-light bg-dark">
      <a><%= link_to "Calendar", root_path, class: "navbar-brand" %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a><%= link_to "Home", index_path, class: "nav-link" %></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Eventos
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a><%= link_to "Ver Eventos", meetings_path, class: "dropdown-item" %></a>
                <a><%= link_to "Crear Eventos", new_meeting_path, class: "dropdown-item" %></a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Empleados
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a><%= link_to "Ver Empleados", employees_path, class: "dropdown-item" %></a>
                <a><%= link_to "Crear Empleados", new_employee_path, class: "dropdown-item" %></a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Relaciones
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a><%= link_to "Ver Relaciones", meeting_employees_path, class: "dropdown-item" %></a>
                <a><%= link_to "Crear Relaciones", new_meeting_employee_path, class: "dropdown-item" %></a>
            </div>
          </li>
        </ul>
      </div>  
    </nav>
		<div class="container" style="padding-top: 10px;">
      <%= yield %>
    </div>
	</div>
</html>

app/views/meeting_employees/_form.html.erb
<%= form_with(model: meeting_employee, local: true) do |form| %>
  <% if meeting_employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting_employee.errors.count, "error") %> prohibited this meeting_employee from being saved:</h2>

      <ul>
      <% meeting_employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meeting_id %>
    <%= form.text_field :meeting_id, id: :meeting_employee_meeting_id %>
  </div>

  <div class="field">
    <%= form.label :employee_id %>
    <%= form.text_field :employee_id, id: :meeting_employee_employee_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meeting_employees/edit.html.erb
<h1>Editing Meeting Employee</h1>

<%= render 'form', meeting_employee: @meeting_employee %>

<%= link_to 'Show', @meeting_employee %> |
<%= link_to 'Back', meeting_employees_path %>

app/views/meeting_employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meeting Employees</h1>

<table>
  <thead>
    <tr>
      <th>Meeting</th>
      <th>Employee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meeting_employees.each do |meeting_employee| %>
      <tr>
        <td><%= meeting_employee.meeting %></td>
        <td><%= meeting_employee.employee %></td>
        <td><%= link_to 'Show', meeting_employee %></td>
        <td><%= link_to 'Edit', edit_meeting_employee_path(meeting_employee) %></td>
        <td><%= link_to 'Destroy', meeting_employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting Employee', new_meeting_employee_path %>

app/views/meeting_employees/new.html.erb
<h1>New Meeting Employee</h1>

<%= render 'form', meeting_employee: @meeting_employee %>

<%= link_to 'Back', meeting_employees_path %>

app/views/meeting_employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Meeting:</strong>
  <%= @meeting_employee.meeting %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @meeting_employee.employee %>
</p>

<%= link_to 'Edit', edit_meeting_employee_path(@meeting_employee) %> |
<%= link_to 'Back', meeting_employees_path %>

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :meeting_title %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.datetime_select :start, id: :meeting_start %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.datetime_select :end, id: :meeting_end %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.color_field :color, id: :meeting_color %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', index_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meetings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start</th>
      <th>End</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.title %></td>
        <td><%= meeting.start %></td>
        <td><%= meeting.end %></td>
        <td><%= meeting.color %></td>
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path %>
<%= link_to 'Back', index_path %>

app/views/meetings/json_employee.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Employees</title>
</head>

<body>
	<div class="container">
		<h1>Empleados</h1>
		<table class="table">
			<thead>
    			<tr>
			    	<th scope="col">ID</th>
			    	<th scope="col">Name</th>
			    	<th scope="col">Last Name</th>
			    	<th scope="col">Sex</th>
			    	<th scope="col">Entrada</th>
			    	<th scope="col">Salida</th>
			    	<th scope="col">Eventos</th>
			    </tr>
  			</thead>
		
			<tbody>
				<% @meeting.employee.each do |emp| %>
		  	  		<tr>
	      				<th scope="row"><%= emp.id %></th>
				    	<td><%= emp.name %></td>
				    	<td><%= emp.lastname %></td>
				    	<td><%= emp.sex %></td>
				    	<td><%= emp.start.strftime("%I:%M%p") %></td>
				    	<td><%= emp.end.strftime("%I:%M%p") %></td>
				    	<td>
				    		<!-- <p><%= link_to "#newTag",  data: { toggle: "modal" } do %>
  								<i class="fa fa-plus"></i> Ver Eventos
  								<%= emp.id %> 
								<% end %>
							</p> -->
							<p>
								<%= link_to "Ver Eventos", employee_url(emp) %>
							</p>


							<div id="newTag" class="modal fade" role="dialog">
							  <div class="modal-dialog">
							    <div class="modal-content">
							      <div class="modal-header">
							      	<h2>Ver Eventos</h2>
							        <button type="button" class="close" data-dismiss="modal">&times;</button>
							      </div>
							      <div class="modal-body">
						      	  	<table class="table">
										<thead>
					    					<tr>
								    			<th scope="col">ID</th>
								    			<th scope="col">Title</th>
								    			<th scope="col">Color</th>
								    			<th scope="col">Start</th>
								    			<th scope="col">End</th>
								    		</tr>
					  					</thead>
							
										<tbody>
											<% emp.meeting.each do |mee| %>
									  	  		<tr>
								      				<th scope="row"><%= mee.id %></th>
											    	<td><%= mee.title %></td>
											    	<td><%= mee.color %></td>
											    	<td><%= mee.start %></td>
											    	<td><%= mee.end %></td>
								    			</tr>
					    					<% end %>
										</tbody>
									</table> 	 
							      </div>
							    </div>
							  </div>
							</div>
				    	</td>
	    			</tr>
    			<% end %>
			</tbody>
		</table>  
	</div>
	
	<div class="calendar2"></div>		

</body>
</html>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', index_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @meeting.title %>
</p>

<p>
  <strong>Start:</strong>
  <%= @meeting.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @meeting.end %>
</p>

<p>
  <strong>Color:</strong>
  <%= @meeting.color %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Welcome</title>
</head>
<body>
	
	<div class="calendar">
	</div>

</body>
</html>